### ISSUE TITLE
Please update dependency `debug` to version 2.6.9 or >= 3.1.0

### ISSUE THREAD

**Issue by HowWeRollingham** [mickhansen/retry-as-promised#10]
Current version of `debug` dependency is 2.2.0 which is subject to a [ReDOS Vulnerability](https://nodesecurity.io/advisories/534)

Upgrading to either 2.6.9 or any version later than 3.1.0 will address this.

**Comment by jarrodconnolly** [comment]
This package is depended on by others, and comes up in security scans now.
Would love to see this pull request merged.

https://snyk.io/vuln/npm:debug:20170905

**Comment by mickhansen** [comment]
https://github.com/mickhansen/retry-as-promised/pull/11 merged
