### ISSUE TITLE
Confusion about initial delay

### ISSUE THREAD

**Issue by barwin** [mickhansen/retry-as-promised#12]
Hello,

First off thanks for a very useful module!

In this snippet/example from the README:
```
backoffBase: 1000 // Initial backoff duration in ms. Default: 100,
backoffExponent: 1.5 // Exponent to increase backoff each try. Default: 1.1
```

The example in the README threw me off because after testing it out, I noticed the initial retry delay is not 1000ms as I would have expected, but 31,622ms (1000^1.5)

I was just wondering if that was intentional, and if not, I'd be happy to submit a P/R that uses the unmodified `backoffBase` for the initial retry delay, only increasing on subsequent retries.

Cheers,
-Ben

**Comment by mickhansen** [comment]
That sounds like a unintentional bug, the initial delay should definitely be the base.

**Comment by barwin** [comment]
Thanks for the quick reply @mickhansen, I've opened #13 for your review
