### ISSUE TITLE
Update or remove `debug`

### ISSUE THREAD

**Issue by SimonSchick** [mickhansen/retry-as-promised#19]
Not much to add, not sure why this library needs `debug` the consumer should handle these kind of messages.
Otherwise I'd ask you to update to 3.x.x of `debug`, as the use of your package in `sequelize` causes multiple installs of the `debug` package when used in combination with packages such as `ioredis`.

**Comment by SimonSchick** [comment]
ping @mickhansen

**Comment by mickhansen** [comment]
Quite a few packages use `debug`, and this package is used in other packages than just sequelize.
However `debug` isn't strictly necessary here and i'd welcome a PR that removes it.
