### ISSUE TITLE
$current not exposed on Options.report callback signature type

### ISSUE THREAD

**Issue by leaumar** [mickhansen/retry-as-promised#39]
Picture says a thousand words (not just of code):
![image](https://user-images.githubusercontent.com/3950300/217120559-2ba083cf-5dd1-4438-a551-aeb4f4af92a4.png)

Because `retryAsPromised` is typed as taking `Options`, and `Options` declares `report` as `((message: string, obj: Options, err?: any) => void) | undefined;` (taking `Options` instead of `CoercedOptions`), the report callback can't officially access the `$current` property to report the number of retries had, but a simple repl test (`retry.default(() => Promise.reject(new Error("kaboom")), {report: (msg,conf, err) => console.error({msg,conf,err}), max: 1})`) shows that it's there. `CoercedOptions` also isn't exported to allow manual casting either.

Could the types be fixed to expose `$current` in the right place, please?

**Comment by mickhansen** [comment]
The typing for `report` needs to be changed to use `CoercedOptions` it appears.

**Comment by mickhansen** [comment]
Fixed in `v7.0.4`

**Comment by leaumar** [comment]
😍 thanks for the quick publish
